apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-arkiv-adapter-simulator
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-arkiv-adapter-simulator
    app.kubernetes.io/instance: fint-arkiv-adapter-simulator_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-arkiv-adapter-simulator:sha-0000000
  url:
    hostname: flyt.vigoiks.no
    basePath: path
  ingress:
    enabled: true
    basePath: path
#    middlewares:
#      - fint-flyt-auth-forward-sso
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError'
  onePassword:
    itemPath: path
  resources:
    limits:
      memory: "256Mi"
      cpu: "100m"
    requests:
      memory: "256Mi"
      cpu: "100m"
  probes:
    startup:
      path: /
      port: 8080
      initialDelaySeconds: 70
      failureThreshold: 12
      periodSeconds: 10
      timeoutSeconds: 3
    readiness:
      path: /
      port: 8080
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3
    liveness:
      path: /
      port: 8080
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  observability:
    metrics:
      enabled: true
      port: "8080"
      path: /actuator/prometheus
  prometheus:
    enabled: true
    port: "8080"
    path: /actuator/prometheus
