apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: fint-arkiv-adapter-simulator
    namespace: fintlabs-no
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: fint-arkiv-adapter-simulator
    minReplicas: 1
    maxReplicas: 3
    metrics:
        -   type: Resource
            resource:
                name: cpu
                target:
                    type: Utilization
                    averageUtilization: 90
